export const SnowJS = [
  { text: "+", left: (window.innerWidth / 20) * 1 },
  { text: "*", left: (window.innerWidth / 20) * 2 },
  { text: "×", left: (window.innerWidth / 20) * 3 },
  { text: "+", left: (window.innerWidth / 20) * 4 },
  { text: "*", left: (window.innerWidth / 20) * 5 },
  { text: "×", left: (window.innerWidth / 20) * 6 },
  { text: "+", left: (window.innerWidth / 20) * 7 },
  { text: "*", left: (window.innerWidth / 20) * 8 },
  { text: "×", left: (window.innerWidth / 20) * 9 },
  { text: "+", left: (window.innerWidth / 20) * 10 },
  { text: "*", left: (window.innerWidth / 20) * 11 },
  { text: "×", left: (window.innerWidth / 20) * 12 },
  { text: "+", left: (window.innerWidth / 20) * 13 },
  { text: "*", left: (window.innerWidth / 20) * 14 },
  { text: "×", left: (window.innerWidth / 20) * 15 },
  { text: "+", left: (window.innerWidth / 20) * 16 },
  { text: "*", left: (window.innerWidth / 20) * 17 },
  { text: "×", left: (window.innerWidth / 20) * 18 },
];
